# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The city name.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The country name.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The school name.', max_length=255)),
                ('site', models.URLField(default='', help_text='The school website.')),
                ('mailRegex', models.CharField(default='', help_text='The regex for the email that the students use.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The university name.', max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unichat.City')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="The user's academic email.", max_length=254, unique=True)),
                ('gender', models.IntegerField(choices=[(-1, 'Male'), (0, 'Undefined'), (1, 'Female')], default=0, help_text="The user's gender, by default UNDEFINED, unless otherwise explicitly specified by the user.")),
                ('interestedInGender', models.IntegerField(choices=[(-1, 'Male'), (0, 'Undefined'), (1, 'Female')], default=0, help_text='The gender that the user is interested in talking to, by default UNDEFINED.')),
                ('cookie', models.CharField(db_index=True, default='', help_text="The user's active cookie.", max_length=255)),
                ('interestedInSchools', models.ManyToManyField(related_name='user_interested_schools', to='unichat.School')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unichat.School')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unichat.University'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unichat.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('country', 'name')]),
        ),
    ]
