# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimeet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcomeToken',
            field=models.CharField(db_index=True, default='', help_text='The one-time authentication token used in welcome link.', max_length=255),
        ),
    ]
