# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimeet', '0002_user_welcometoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The service name.', max_length=255)),
                ('token', models.CharField(db_index=True, default='', help_text='The service UId token.', max_length=255)),
                ('activeUsers', models.IntegerField(default=0, help_text='The connected users.')),
            ],
        ),
    ]
