# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimeet', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registrationIP',
            field=models.GenericIPAddressField(db_index=True, default='127.0.0.1', help_text='The IP that the user used for registration.'),
        ),
    ]
